CREATE TABLE CAKES(
  CAKE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(26) NOT NULL,
  TYPE VARCHAR(16) NOT NULL UNIQUE,
  SERVINGS INT(2) NOT NULL
);

CREATE TABLE BIRIYANI(
  BIRIYANI_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(26) NOT NULL,
  TYPE VARCHAR(16) NOT NULL UNIQUE,
  SERVINGS INT(2) NOT NULL
);

CREATE TABLE DESERTS(
  DESERT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(26) NOT NULL,
  TYPE VARCHAR(16) NOT NULL UNIQUE,
  SERVINGS INT(2) NOT NULL
);

